twoweek/accounts/urls.py
from django.urls import path, include
from django.views.generic import RedirectView
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', include('django.contrib.auth.urls')),
    path('', views.Index.as_view(), name='index'),
    path('profile/', views.profile.as_view(), name='profile'),
    path('register/', views.register, name='register'),
    path('error/', views.get_error,name='error'),
    path('error_update/', views.get_error_update,name='error_update'),
    path('profile/applications', views.view_applications.as_view(), name='profile_applications'),
    path('profile/main_applications', views.profile_main_applications.as_view(), name='profile_main_applications'),
    path('profile/applications/create', views.create_application.as_view(), name='profile_applications_create'),
    path('profile/applications/<int:pk>/',views.detail_application.as_view(), name='profile_application_detail'),
    path('profile/applications/<int:pk>/delete',views.delete_application.as_view(), name='profile_application_delete'),
    path('profile/applications/<int:pk>/update', views.update_application.as_view(), name='profile_application_update')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twoweek/twoweek/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url='/accounts/', permanent=True)),
    path('user/', include('django.contrib.auth.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

twoweek/accounts/models.py
from django.db import models
from datetime import datetime
from email.policy import default
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.urls import reverse


# Создаем класс менеджера пользователей
class MyUserManager(BaseUserManager):
    # Создаём метод для создания пользователя
    def _create_user(self, email, username, password, **extra_fields):
        # Проверяем есть ли Email
        if not email:
            # Выводим сообщение в консоль
            raise ValueError("Вы не ввели Email")
        # Проверяем есть ли логин
        if not username:
            # Выводим сообщение в консоль
            raise ValueError("Вы не ввели Логин")
        # Делаем пользователя
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            **extra_fields,
        )
        # Сохраняем пароль
        user.set_password(password)
        # Сохраняем всё остальное
        user.save(using=self._db)
        # Возвращаем пользователя
        return user

    # Делаем метод для создание обычного пользователя
    def create_user(self, email, username, password):
        # Возвращаем нового созданного пользователя
        return self._create_user(email, username, password)

    # Делаем метод для создание админа сайта
    def create_superuser(self, email, username, password):
        # Возвращаем нового созданного админа
        return self._create_user(email, username, password, is_staff=True, is_superuser=True)


class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Введите категорию заявки')

    def __str__(self):
        return self.name


class User(AbstractBaseUser, PermissionsMixin):
    id = models.AutoField(primary_key=True, unique=True)
    full_name = models.CharField(max_length=50, help_text="Напишите ФИО")
    username = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=200)
    email = models.EmailField(unique=True, max_length=254)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'  # Идентификатор для обращения
    REQUIRED_FIELDS = ['email']  # Список имён полей для Superuser

    objects = MyUserManager()

    def __str__(self):
        return self.full_name


class Application(models.Model):
    id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
    title = models.CharField(max_length=200, verbose_name='Название')
    desc = models.TextField(max_length=400, verbose_name='Описание')
    img = models.ImageField(upload_to='img', verbose_name='Картинка')
    ready_design = models.ImageField(upload_to='design', verbose_name='Готовый дизайн', null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name='Пользователь', null=True, blank=True,
                             to_field='id')
    date = models.DateField(default=datetime.today())
    comment = models.TextField(max_length=400, verbose_name='Комментарий', null=True, blank=True)

    NEW = 'new'
    LOAD = 'load'
    READY = 'ready'
    LOAN_STATUS = (
        (NEW, 'Новая'),
        (LOAD, 'Принято в работу'),
        (READY, 'Выполнено'),
    )

    status = models.CharField(max_length=30, choices=LOAN_STATUS, default='new', help_text='Статус',
                              verbose_name='Статус')

    SKETCH = 'sketch'
    MID_DETAIL = 'mid_detail'
    AUTHOR = 'author'
    CATEGORIES = (
        (SKETCH, 'Эскизный проект'),
        (MID_DETAIL, 'Средняя детализация'),
        (AUTHOR, 'Авторский интерьер'),
    )

    category = models.CharField(max_length=30, choices=CATEGORIES, default='Эскизный проект', help_text='Категории',
                                verbose_name='Категории')

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # Тут мы создали новый метод
        return reverse('profile_application_detail', args=[str(self.id)])

twoweek/accounts/forms.py
from .models import Application, User
from django import forms
from django.core.validators import RegexValidator, EmailValidator

class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput,
    validators=[RegexValidator(r'[a-zA-Z\-]','В логине доступны только латинские символы')], required=True)

    full_name = forms.CharField(label='ФИО', widget=forms.TextInput, 
    validators=[RegexValidator(r'[а-яА-ЯёЁ\-\s]','В ФИО доступна только кириллица, пробелы и дефис')], required=True)
    
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput, required=True)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput, required=True)
    email = forms.EmailField(label='Email',widget=forms.EmailInput,required=True, validators=[EmailValidator('Email не верен')])
    checkbox = forms.CharField(label='Согласие на обработку персональных данных', widget=forms.CheckboxInput, required=False)

    class Meta:
        model = User
        fields = ('username','email', 'full_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают')
        return cd['password2']
    
    def clean_checkbox(self):
        cd = self.cleaned_data
        print(cd['checkbox'])
        if cd['checkbox'] == False:
            raise forms.ValidationError('Подтвердите обработку персональных данных')
        return cd['checkbox']

class ApplicationCreateForm(forms.ModelForm):
    title = forms.CharField(label='Название',widget=forms.TextInput)
    desc = forms.CharField(label='Описание', widget=forms.TextInput)

    
    class Meta:
        model = Application
        fields = ('title', 'desc', 'img')

twoweek/accounts/views.py
from django.shortcuts import render
from urllib import request
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.utils.translation import gettext_lazy as _
from .forms import UserRegistrationForm, ApplicationCreateForm
from django.views import generic
from .models import Application
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy, reverse


class Index(generic.ListView):
    model = Application
    template_name = 'index.html'
    paginate_by = 5

    def get_queryset(self):
        return Application.objects.filter(status='ready')
        
    def index(request):
        application_list = Application.objects.all()
        return render(
        request, 'index.html', {"application_list": application_list})

def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            # Create a new user object but avoid saving it yet
            new_user = user_form.save(commit=False)
            # Set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            # Save the User object
            new_user.save()
            return render(request, 'registration/register_done.html', {'new_user': new_user})

    else:
        user_form = UserRegistrationForm()
    return render(request, 'registration/register.html', {'user_form': user_form})


def password_reset(request):
    return render(
        request,
        'registration/password_reset.html'
    )


class profile(generic.ListView):
    model = Application
    template_name = 'registration/profile.html'
    paginate_by = 5

    def get_queryset(self):
        ordering = self.request.GET.get('orderby')
        if ordering == 'Выполнено':
            ordering = 'ready'
        elif ordering == 'Принято в работу':
            ordering = 'load'
        elif ordering == 'Новая':
            ordering = 'new'
        elif ordering == 'Все':
            ordering = ''
        if ordering == '' or ordering == None:
            if self.request.user.is_staff:
                return Application.objects.filter()
            else:
                return Application.objects.filter(user__exact=self.request.user.id)
        else:
            if self.request.user.is_staff:
                return Application.objects.filter(status=ordering)
            else:
                return Application.objects.filter(user__exact=self.request.user.id, status=ordering)


def login(request):
    return render(
        request,
        'registration/profile.html'
    )


class view_applications(generic.ListView):
    model = Application
    template_name = 'aplications/application_list.html'
    paginate_by = 5

    def get_queryset(self):
        ordering = self.request.GET.get('orderby')
        if ordering == 'Выполнено':
            ordering = 'ready'
        elif ordering == 'Принято в работу':
            ordering = 'load'
        elif ordering == 'Новая':
            ordering = 'new'
        elif ordering == 'Все':
            ordering = ''
        if ordering == '' or ordering == None:
            if self.request.user.is_staff:
                return Application.objects.filter()
            else:
                return Application.objects.filter(user__exact=self.request.user.id)
        else:
            if self.request.user.is_staff:
                return Application.objects.filter(status=ordering)
            else:
                return Application.objects.filter(user__exact=self.request.user.id, status=ordering)


def get_error(request):
    return render(
        request,
        'aplications/error.html'
    )


class profile_main_applications(generic.ListView):
    model = Application
    template_name = 'aplications/application_list.html'
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['count_of_load'] = Application.objects.filter(status='load').count()
        context['is_main'] = True;
        return context

    def get_queryset(self):
        return Application.objects.filter(status='ready')


class create_application(CreateView):
    model = Application
    template_name = 'aplications/application_form.html'
    fields = ('title', 'desc', 'img')

    def form_valid(self, form):
        fields = form.save(commit=True)
        fields.user = self.request.user
        fields.save()

        return super().form_valid(form)


class detail_application(DetailView):
    model = Application
    template_name = 'aplications/application_detail.html'


class delete_application(DeleteView):
    model = Application
    template_name = 'aplications/application_confirm_delete.html'
    success_url = reverse_lazy('profile_applications')
    success_msg = 'Запись удалена'

    def form_valid(self, form):
        print(self.object.status)
        if self.object.status != 'new':
            return redirect('error')
        else:
            self.object.delete()
            success_url = reverse_lazy('profile_applications')
            success_msg = 'Запись удалена'
            return HttpResponseRedirect(success_url, success_msg)


class update_application(UpdateView):
    model = Application
    fields = ('status', 'ready_design', 'category', 'comment')
    template_name = 'aplications/application_update.html'
    

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.object.status == 'ready':
            context['is_ready'] = True
            context['is_new'] = False
            context['is_load'] = False
        
            
        elif self.object.status == 'load':
            context['is_load'] = True
            context['is_new'] = False
            context['is_ready'] = False
        
        elif self.object.status == 'new':
            context['is_new'] = True
            context['is_ready'] = False
            context['is_load'] = False
        else:
            self.object.save()
            success_url = reverse_lazy('profile_applications')
            success_msg = 'Запись обновлена'
            return HttpResponseRedirect(success_url, success_msg)
        return context
    

    def form_valid(self, form):
        print(self.object.status)

        if self.object.status != 'ready':
            return redirect('error_update')

        else:
            self.object.save()
            success_url = reverse_lazy('profile_applications')
            success_msg = 'Запись обновлена'
            return HttpResponseRedirect(success_url, success_msg)
            

def get_error_update(request):
    return render(
        request,
        'aplications/error_update.html'
    )

twoweek/accounts/templates/aplications/application_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Удалить заявку</h1>

<p>Вы уверены, что хотите удалить заявку: {{ application.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Да, удалить" />
</form>
<h1>{{ error }}</h1>
{% endblock %}

twoweek/accounts/templates/aplications/application_detail.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
    <link rel="stylesheet" href="{% static 'application_detail.css'%}">
{% endblock %}
{% block title %}{% endblock %}
{% block content %}
<h1>Название заявки {{ application.title }}</h1>
<h2>Описание: {{ application.desc }}</h2>
<div class="block">
    <img class="bd-placeholder-img flex-shrink-0 me-2 rounded"  src="../../..{{ application.img.url }}" alt="" width="700px">
    {% if ready_design %}
        <img class="bd-placeholder-img flex-shrink-0 me-2 rounded"  src="../../..{{ application.ready_design.url }}" alt="" width="700px">
    {% endif %}
</div>
<h3>Комментарий:</h3>
<p>{{ application.comment }}</p>
<h3>{{ application.get_status_display }}, {{ application.get_category_display }} {% if user.is_staff %}Пользователь : {{ application.user.get_username }}{% endif %}</h3>
{% if user.is_staff %}<a href="{% url 'profile_application_update' application.id %}">Изменить</a>{% endif %}
{% endblock %}

twoweek/accounts/templates/aplications/application_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{% endblock %}
{% block content %}
{{ wh_status }}
<form action="" method="post" enctype="multipart/form-data">   
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Создать" class="btn btn-success"/>
</form>
{% endblock %}

twoweek/accounts/templates/aplications/application_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block links %}
<link rel="stylesheet" href="{% static 'style.css'%}">
{% endblock %}
{% block content %}
{% if is_main %}
<h1>Заявки</h1>
{% if application_list %}
<h2>Кол-во работ находящихся в обработке: {{ count_of_load }}</h2>
<table class="table align-middle table-edge table-hover table-nowrap mb-0">
  <thead class="thead-light">
      <tr>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="name">
                  Название
              </a>
          </th>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="email">
                  Описание
              </a>
          </th>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="id">
                  Категория
              </a>
          </th>
          <th>
            
          </th>
          {% if user.is_staff %}
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="status">
                  Имя пользователя
              </a>
          </th>
          {% endif %}
          <th class="w-150px min-w-150px">
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="status">
                  Дата создания
              </a>
          </th>
      </tr>
  </thead>
  <tbody class="list">
    {% for application in application_list %}
      <tr>
          <td>
              <div class="avatar avatar-circle avatar-xs me-2">
                  <img src="..{{ application.img.url }}" alt="..." class="avatar-img" width="30" height="30">
              </div>
          <span class="name fw-bold">{{ application.title }}</span>
          </td>
          <td class="email">{{ application.desc }}</td>
          <td class="category">{{ application.get_category_display }}</td>
          <td class="status">{{ application.get_status_display }}<span class="legend-circle bg-success"></span></td>
          {% if user.is_staff %}
            <td class="name fw-bold">{{ application.user.get_username }}</td>
          {% endif %}
          <td class="date" data-signed="1648252800">03.26.2022</td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% endif %}
{% else %}
{% if request.user.is_authenticated %}

<h1>Заявки</h1>
{% if request.user.is_authenticated %}
<a href="{% url 'profile_applications_create' %}">Создать заявку</a>
<div>
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
  {% else %}
    <a href="#">Предыдущая страница</a>
  {% endif %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следуюшая страница</a>
  {% else %}
    <a href="#">Следуюшая страница</a>
  {% endif %}
</div>
{% endif %}
<h3>Сортировка по статусу:</h3>
<form action="{% url 'profile_applications' %}" method="get">
    <input type="submit" name="orderby" value="Все">
    <input type="submit" name="orderby" value="Новая">
    <input type="submit" name="orderby" value="Принято в работу">
    <input type="submit" name="orderby" value="Выполнено">
</form><br>
{% if application_list %}
<table class="table align-middle table-edge table-hover table-nowrap mb-0">
  <thead class="thead-light">
      <tr>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="name">
                  Название
              </a>
          </th>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="email">
                  Описание
              </a>
          </th>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="id">
                  Категория
              </a>
          </th>
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="date">
                  Статус
              </a>
          </th>
          {% if user.is_staff %}
          <th>
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="status">
                  Имя пользователя
              </a>
          </th>
          {% endif %}
          <th class="w-150px min-w-150px">
              <a href="javascript: void(0);" class="text-muted list-sort" data-sort="status">
                  Дата создания
              </a>
          </th>
          <th class="w-150px min-w-150px">
            <a href="javascript: void(0);" class="text-muted list-sort" data-sort="status">
                Удалить заявку
            </a>
        </th>
      </tr>
  </thead>
  <tbody class="list">
    {% for application in application_list %}
      <tr>
          <td>
              <div class="avatar avatar-circle avatar-xs me-2">
                  <img src="..{{ application.img.url }}" alt="..." class="avatar-img" width="30" height="30">
              </div>
          <a class="name fw-bold" href="{{ application.get_absolute_url }}">{{ application.title }}</a>
          </td>
          <td class="email">{{ application.desc }}</td>
          <td class="category">{{ application.get_category_display }}</td>
          <td class="status">{{ application.get_status_display }}<span class="legend-circle bg-success"></span></td>
          {% if user.is_staff %}
            <td class="name fw-bold">{{ application.user.get_username }}</td>
          {% endif %}
          <td class="date" data-signed="1648252800">03.26.2022</td>
          <td class="date"><a href="{% url 'profile_application_delete' application.id %}">Удалить</a></td>
      </tr>
      {% endfor %}
    </tbody>
</table>
{% endif %}
{% else %}
<div class="block__footer">
  <h1>Чтобы просмотреть заявки вам нужно авторизироваться.</h1>
  <button><a href="{% url 'login'%}">Войти</a></button>
</div>
{% endif %}
{% endif %}
{% if request.user.is_authenticated %}
<div>
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">Предыдущая страница</a>
  {% else %}
    <a href="#">Предыдущая страница</a>
  {% endif %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">Следуюшая страница</a>
  {% else %}
    <a href="#">Следуюшая страница</a>
  {% endif %}
</div>
{% endif %}

{%endblock%}

twoweek/accounts/templates/aplications/application_update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block tilte %}Изменить заявку{% endblock %}
{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.status|as_crispy_field }}
        {{ form.category|as_crispy_field }}
        {% if is_ready %}
            {{ form.ready_design|as_crispy_field }}
        {% endif %}
        {% if is_load %}
            {{ form.comment|as_crispy_field }}
        {% endif %}
        <input type="submit" value="Изменить" class="btn btn-success">
    </form>
{% endblock %}

twoweek/accounts/templates/aplications/error.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ success_msg }}{% endblock %}
{% block content %}
<h1>[ОШИБКА] Запись не удалена!</h1>
<h4>Так как данная запись имеет статус "Выполнено" или "Принято в работу"</h4>
{% endblock %}

twoweek/accounts/templates/aplications/error_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ success_msg }}{% endblock %}
{% block content %}
<h1>Запись не обновлена!</h1>
<h4>Так как данная запись имеет статус "Выполнено"</h4>
{% endblock %}